#!/usr/bin/env python3
"""Introspect BIRD PostgreSQL and emit Debezium + Doris CDC artifacts."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIG_ENV = ROOT / "config" / "bird_minidev_schemas.env"
OUT_CONNECTOR = ROOT / "stack" / "connectors" / "bird-postgres-source.json"
OUT_PUBLICATIONS = ROOT / "stack" / "bird" / "init" / "z99_publications.sql"
OUT_ODS = ROOT / "stack" / "doris" / "10_ods_tables.sql"
OUT_ROUTINE = ROOT / "stack" / "doris" / "20_routine_loads.sql"
OUT_VIEWS = ROOT / "stack" / "doris" / "analytics_schema.sql"

TOPIC_PREFIX = "bird-minidev-pg"
DORIS_DB = "bird_minidev_olap"

PG_TO_DORIS = {
    "smallint": "INT",
    "integer": "INT",
    "bigint": "BIGINT",
    "real": "FLOAT",
    "double precision": "DOUBLE",
    "numeric": "DECIMAL(38,9)",
    "boolean": "BOOLEAN",
    "text": "STRING",
    "character varying": "STRING",
    "varchar": "STRING",
    "character": "STRING",
    "date": "DATE",
    "timestamp without time zone": "DATETIME",
    "timestamp with time zone": "DATETIME",
    "json": "STRING",
    "jsonb": "STRING",
    "uuid": "STRING",
    "bytea": "STRING",
}


def load_schemas() -> list[str]:
    text = CONFIG_ENV.read_text(encoding="utf-8")
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("DB_ALLOWED_SCHEMAS="):
            return [s.strip() for s in line.split("=", 1)[1].split(",") if s.strip()]
    raise SystemExit(f"DB_ALLOWED_SCHEMAS not found in {CONFIG_ENV}")


def map_type(pg_type: str) -> str:
    t = pg_type.lower().strip()
    if t in PG_TO_DORIS:
        return PG_TO_DORIS[t]
    if t.startswith("character varying"):
        return "STRING"
    if t.startswith("timestamp"):
        return "DATETIME"
    return "STRING"


def doris_column_name(name: str) -> str:
    """Sanitize identifiers to Doris column-name regex (no parentheses etc.)."""
    # Allowed roughly: start [_a-zA-Z@0-9 /], then [.a-zA-Z0-9_+-/?@#$%^&*" ,:]
    cleaned = re.sub(r"[^\w\s/.\-+/?@#$%^&*\"\s,:]", "_", name)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_ ")
    if not cleaned:
        cleaned = "col"
    if not re.match(r"^[_a-zA-Z@0-9\s/]", cleaned):
        cleaned = f"_{cleaned}"
    return cleaned[:255]


def ods_name(schema: str, table: str) -> str:
    return f"ods_{schema}_{table}"


def fetch_tables(conn, schemas: list[str]) -> list[tuple[str, str, list[tuple[str, str]]]]:
    import psycopg

    rows: list[tuple[str, str, list[tuple[str, str]]]] = []
    with conn.cursor() as cur:
        for schema in schemas:
            cur.execute(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = %s AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """,
                (schema,),
            )
            for (table_name,) in cur.fetchall():
                cur.execute(
                    """
                    SELECT column_name, data_type
                    FROM information_schema.columns
                    WHERE table_schema = %s AND table_name = %s
                    ORDER BY ordinal_position
                    """,
                    (schema, table_name),
                )
                cols = [(r[0], r[1]) for r in cur.fetchall()]
                rows.append((schema, table_name, cols))
    return rows


def emit_publications(tables: list[tuple[str, str, list]]) -> str:
    # Debezium default publication.name is dbz_publication; keep a single pub.
    lines = [
        "-- Generated by scripts/codegen/generate_cdc.py",
        "DROP PUBLICATION IF EXISTS dbz_publication;",
        "CREATE PUBLICATION dbz_publication FOR TABLE",
    ]
    qualified = [f'    "{schema}"."{table}"' for schema, table, _ in tables]
    lines.append(",\n".join(qualified) + ";")
    lines.append("")
    return "\n".join(lines)


def emit_connector(tables: list[tuple[str, str, list]], pg_host: str) -> dict:
    include = [f"{s}.{t}" for s, t, _ in tables]
    return {
        "name": "bird-minidev-postgres",
        "config": {
            "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
            "database.hostname": "BIRD_PG_HOST_PLACEHOLDER",
            "database.port": "5432",
            "database.user": "debezium",
            "database.password": "debezium",
            "database.dbname": "bird",
            "topic.prefix": TOPIC_PREFIX,
            "plugin.name": "pgoutput",
            "publication.autocreate.mode": "disabled",
            "publication.name": "dbz_publication",
            "slot.name": "dbz_bird_minidev",
            "table.include.list": ",".join(include),
            "transforms": "unwrap",
            "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
            "transforms.unwrap.drop.tombstones": "false",
            "transforms.unwrap.delete.handling.mode": "rewrite",
            "transforms.unwrap.add.fields": "source.ts_ms",
        },
    }


def emit_ods_ddl(tables: list[tuple[str, str, list]]) -> str:
    lines = [
        "-- Generated by scripts/codegen/generate_cdc.py",
        f"USE {DORIS_DB};",
        "",
    ]
    for schema, table, cols in tables:
        name = ods_name(schema, table)
        safe_cols = [(doris_column_name(c[0]), c[0], c[1]) for c in cols]
        key_col = safe_cols[0][0] if safe_cols else "id"
        col_defs = []
        for safe, _orig, ctype in safe_cols:
            doris_t = map_type(ctype)
            if safe == key_col and doris_t == "STRING":
                doris_t = "VARCHAR(65533)"
            col_defs.append(f"    `{safe}` {doris_t}")
        col_defs.append("    `__deleted` BOOLEAN")
        col_defs.append("    `__source_ts_ms` BIGINT")
        lines.append(
            f"CREATE TABLE IF NOT EXISTS `{name}` (\n"
            + ",\n".join(col_defs)
            + f"\n) DUPLICATE KEY(`{key_col}`) DISTRIBUTED BY HASH(`{key_col}`) BUCKETS 4\n"
            + 'PROPERTIES ("replication_num" = "1");'
        )
        lines.append("")
    return "\n".join(lines)


def _raw_ident(safe: str) -> str:
    """Doris intermediate column name (no hyphens/spaces)."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", f"__raw_{safe}")


def emit_routine_loads(tables: list[tuple[str, str, list]]) -> str:
    """Emit routine loads for Kafka Connect JSON (schema+payload) + Debezium unwrap.

    Connect JsonConverter wraps rows as {\"schema\":..., \"payload\":{...}}.
    DATE fields arrive as epoch days; DATETIME as epoch millis.
    ``__source_ts_ms`` is omitted from JSON (nullable ODS column).
    """
    lines = [
        "-- Generated by scripts/codegen/generate_cdc.py",
        f"USE {DORIS_DB};",
        "",
    ]
    for schema, table, cols in tables:
        name = ods_name(schema, table)
        topic = f"{TOPIC_PREFIX}.{schema}.{table}"
        col_exprs: list[str] = []
        json_fields: list[str] = []
        for orig, ctype in cols:
            safe = doris_column_name(orig)
            doris_t = map_type(ctype)
            if doris_t == "DATE":
                raw = _raw_ident(safe)
                json_fields.append(orig)
                col_exprs.append(raw)
                col_exprs.append(f"`{safe}`=days_add('1970-01-01', {raw})")
            elif doris_t == "DATETIME":
                raw = _raw_ident(safe)
                json_fields.append(orig)
                col_exprs.append(raw)
                col_exprs.append(f"`{safe}`=from_unixtime({raw}/1000)")
            else:
                json_fields.append(orig)
                col_exprs.append(f"`{safe}`")
        json_fields.append("__deleted")
        col_exprs.append("__raw_deleted")
        col_exprs.append("`__deleted`=(__raw_deleted='true')")
        # Keep ODS `__source_ts_ms` nullable; Connect payload may lack it.
        json_paths = ", ".join(f'\\"$.{f}\\"' for f in json_fields)
        jsonpaths = f"[{json_paths}]"
        cols_sql = ", ".join(col_exprs)
        lines.append(
            f"""CREATE ROUTINE LOAD {name}_load ON {name}
COLUMNS({cols_sql})
PROPERTIES (
    "format" = "json",
    "json_root" = "$.payload",
    "jsonpaths" = "{jsonpaths}",
    "max_batch_interval" = "10",
    "max_error_number" = "1000000"
)
FROM KAFKA (
    "kafka_broker_list" = "kafka:9092",
    "kafka_topic" = "{topic}",
    "property.group.id" = "doris_{name}",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);"""
        )
        lines.append("")
    return "\n".join(lines)


def emit_views(tables: list[tuple[str, str, list]]) -> str:
    lines = [
        "-- Generated by scripts/codegen/generate_cdc.py",
        f"USE {DORIS_DB};",
        "-- NL2SQL: query schema.table names aligned with PostgreSQL (views over ODS).",
        "",
    ]
    schemas = sorted({schema for schema, _, _ in tables})
    for schema in schemas:
        lines.append(f"CREATE DATABASE IF NOT EXISTS `{schema}`;")
    lines.append("")
    for schema, table, cols in tables:
        ods = ods_name(schema, table)
        # Prefer original names as aliases when legal; otherwise sanitized.
        projections = []
        for cname, _ctype in cols:
            safe = doris_column_name(cname)
            if safe == cname:
                projections.append(f"`{safe}`")
            else:
                # Alias may still be illegal; expose sanitized name only.
                projections.append(f"`{safe}`")
        col_list = ", ".join(projections) if projections else "*"
        lines.append(
            f"CREATE VIEW IF NOT EXISTS `{schema}`.`{table}` AS "
            f"SELECT {col_list} FROM `{DORIS_DB}`.`{ods}` "
            f"WHERE COALESCE(`__deleted`, false) = false;"
        )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pg-dsn",
        default=os.environ.get("PG_DSN", "postgresql://bird:bird@127.0.0.1:55432/bird"),
    )
    parser.add_argument("--pg-host", default="bird-postgres", help="hostname in connector JSON")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    schemas = load_schemas()
    try:
        import psycopg

        with psycopg.connect(args.pg_dsn) as conn:
            tables = fetch_tables(conn, schemas)
    except Exception as exc:
        print(f"WARNING: could not connect to PostgreSQL ({exc}); skipping write.")
        return

    if not tables:
        raise SystemExit("No tables found for configured schemas")

    OUT_PUBLICATIONS.write_text(emit_publications(tables), encoding="utf-8")
    connector = emit_connector(tables, args.pg_host)
    OUT_CONNECTOR.write_text(json.dumps(connector, indent=2) + "\n", encoding="utf-8")
    OUT_ODS.write_text(emit_ods_ddl(tables), encoding="utf-8")
    OUT_ROUTINE.write_text(emit_routine_loads(tables), encoding="utf-8")
    OUT_VIEWS.write_text(emit_views(tables), encoding="utf-8")
    print(f"Generated CDC artifacts for {len(tables)} tables.")


if __name__ == "__main__":
    main()
