-- CDC replication user (publications generated by scripts/codegen/generate_cdc.py → z99_publications.sql)

CREATE USER debezium WITH PASSWORD 'debezium' REPLICATION;
GRANT CONNECT ON DATABASE bird TO debezium;

DO $$
DECLARE
  s text;
BEGIN
  FOR s IN
    SELECT nspname FROM pg_namespace
    WHERE nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
      AND nspname NOT LIKE 'pg_%'
  LOOP
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO debezium', s);
    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO debezium', s);
    EXECUTE format(
      'ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO debezium',
      s
    );
  END LOOP;
END $$;
