-- Generated by scripts/codegen/generate_cdc.py
USE bird_minidev_olap;

CREATE TABLE IF NOT EXISTS `ods_california_schools_frpm` (
    `cdscode` VARCHAR(65533),
    `Academic Year` STRING,
    `County Code` STRING,
    `District Code` BIGINT,
    `School Code` STRING,
    `County Name` STRING,
    `District Name` STRING,
    `School Name` STRING,
    `District Type` STRING,
    `School Type` STRING,
    `Educational Option Type` STRING,
    `NSLP Provision Status` STRING,
    `Charter School _Y/N` BIGINT,
    `Charter School Number` STRING,
    `Charter Funding Type` STRING,
    `irc` BIGINT,
    `Low Grade` STRING,
    `High Grade` STRING,
    `Enrollment _K-12` FLOAT,
    `Free Meal Count _K-12` FLOAT,
    `Percent _%_ Eligible Free _K-12` FLOAT,
    `FRPM Count _K-12` FLOAT,
    `Percent _%_ Eligible FRPM _K-12` FLOAT,
    `Enrollment _Ages 5-17` FLOAT,
    `Free Meal Count _Ages 5-17` FLOAT,
    `Percent _%_ Eligible Free _Ages 5-17` FLOAT,
    `FRPM Count _Ages 5-17` FLOAT,
    `Percent _%_ Eligible FRPM _Ages 5-17` FLOAT,
    `2013-14 CALPADS Fall 1 Certification Status` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`cdscode`) DISTRIBUTED BY HASH(`cdscode`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_california_schools_satscores` (
    `cds` VARCHAR(65533),
    `rtype` STRING,
    `sname` STRING,
    `dname` STRING,
    `cname` STRING,
    `enroll12` BIGINT,
    `numtsttakr` BIGINT,
    `avgscrread` BIGINT,
    `avgscrmath` BIGINT,
    `avgscrwrite` BIGINT,
    `numge1500` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`cds`) DISTRIBUTED BY HASH(`cds`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_california_schools_schools` (
    `cdscode` VARCHAR(65533),
    `ncesdist` STRING,
    `ncesschool` STRING,
    `statustype` STRING,
    `county` STRING,
    `district` STRING,
    `school` STRING,
    `street` STRING,
    `streetabr` STRING,
    `city` STRING,
    `zip` STRING,
    `state` STRING,
    `mailstreet` STRING,
    `mailstrabr` STRING,
    `mailcity` STRING,
    `mailzip` STRING,
    `mailstate` STRING,
    `phone` STRING,
    `ext` STRING,
    `website` STRING,
    `opendate` DATE,
    `closeddate` DATE,
    `charter` BIGINT,
    `charternum` STRING,
    `fundingtype` STRING,
    `doc` STRING,
    `doctype` STRING,
    `soc` STRING,
    `soctype` STRING,
    `edopscode` STRING,
    `edopsname` STRING,
    `eilcode` STRING,
    `eilname` STRING,
    `gsoffered` STRING,
    `gsserved` STRING,
    `virtual` STRING,
    `magnet` BIGINT,
    `latitude` FLOAT,
    `longitude` FLOAT,
    `admfname1` STRING,
    `admlname1` STRING,
    `admemail1` STRING,
    `admfname2` STRING,
    `admlname2` STRING,
    `admemail2` STRING,
    `admfname3` STRING,
    `admlname3` STRING,
    `admemail3` STRING,
    `lastupdate` DATE,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`cdscode`) DISTRIBUTED BY HASH(`cdscode`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_card_games_cards` (
    `id` BIGINT,
    `artist` STRING,
    `asciiname` STRING,
    `availability` STRING,
    `bordercolor` STRING,
    `cardkingdomfoilid` STRING,
    `cardkingdomid` STRING,
    `coloridentity` STRING,
    `colorindicator` STRING,
    `colors` STRING,
    `convertedmanacost` FLOAT,
    `dueldeck` STRING,
    `edhrecrank` BIGINT,
    `faceconvertedmanacost` FLOAT,
    `facename` STRING,
    `flavorname` STRING,
    `flavortext` STRING,
    `frameeffects` STRING,
    `frameversion` STRING,
    `hand` STRING,
    `hasalternativedecklimit` BIGINT,
    `hascontentwarning` BIGINT,
    `hasfoil` BIGINT,
    `hasnonfoil` BIGINT,
    `isalternative` BIGINT,
    `isfullart` BIGINT,
    `isonlineonly` BIGINT,
    `isoversized` BIGINT,
    `ispromo` BIGINT,
    `isreprint` BIGINT,
    `isreserved` BIGINT,
    `isstarter` BIGINT,
    `isstoryspotlight` BIGINT,
    `istextless` BIGINT,
    `istimeshifted` BIGINT,
    `keywords` STRING,
    `layout` STRING,
    `leadershipskills` STRING,
    `life` STRING,
    `loyalty` STRING,
    `manacost` STRING,
    `mcmid` STRING,
    `mcmmetaid` STRING,
    `mtgarenaid` STRING,
    `mtgjsonv4id` STRING,
    `mtgofoilid` STRING,
    `mtgoid` STRING,
    `multiverseid` STRING,
    `name` STRING,
    `number` STRING,
    `originalreleasedate` STRING,
    `originaltext` STRING,
    `originaltype` STRING,
    `otherfaceids` STRING,
    `power` STRING,
    `printings` STRING,
    `promotypes` STRING,
    `purchaseurls` STRING,
    `rarity` STRING,
    `scryfallid` STRING,
    `scryfallillustrationid` STRING,
    `scryfalloracleid` STRING,
    `setcode` STRING,
    `side` STRING,
    `subtypes` STRING,
    `supertypes` STRING,
    `tcgplayerproductid` STRING,
    `text` STRING,
    `toughness` STRING,
    `type` STRING,
    `types` STRING,
    `uuid` STRING,
    `variations` STRING,
    `watermark` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_card_games_foreign_data` (
    `id` BIGINT,
    `flavortext` STRING,
    `language` STRING,
    `multiverseid` BIGINT,
    `name` STRING,
    `text` STRING,
    `type` STRING,
    `uuid` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_card_games_legalities` (
    `id` BIGINT,
    `format` STRING,
    `status` STRING,
    `uuid` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_card_games_rulings` (
    `id` BIGINT,
    `date` DATE,
    `text` STRING,
    `uuid` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_card_games_set_translations` (
    `id` BIGINT,
    `language` STRING,
    `setcode` STRING,
    `translation` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_card_games_sets` (
    `id` BIGINT,
    `basesetsize` BIGINT,
    `block` STRING,
    `booster` STRING,
    `code` STRING,
    `isfoilonly` BIGINT,
    `isforeignonly` BIGINT,
    `isnonfoilonly` BIGINT,
    `isonlineonly` BIGINT,
    `ispartialpreview` BIGINT,
    `keyrunecode` STRING,
    `mcmid` BIGINT,
    `mcmidextras` BIGINT,
    `mcmname` STRING,
    `mtgocode` STRING,
    `name` STRING,
    `parentcode` STRING,
    `releasedate` DATE,
    `tcgplayergroupid` BIGINT,
    `totalsetsize` BIGINT,
    `type` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_badges` (
    `id` BIGINT,
    `userid` BIGINT,
    `name` STRING,
    `date` DATETIME,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_comments` (
    `id` BIGINT,
    `postid` BIGINT,
    `score` BIGINT,
    `text` STRING,
    `creationdate` DATETIME,
    `userid` BIGINT,
    `userdisplayname` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_posthistory` (
    `id` BIGINT,
    `posthistorytypeid` BIGINT,
    `postid` BIGINT,
    `revisionguid` STRING,
    `creationdate` DATETIME,
    `userid` BIGINT,
    `text` STRING,
    `comment` STRING,
    `userdisplayname` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_postlinks` (
    `id` BIGINT,
    `creationdate` DATETIME,
    `postid` BIGINT,
    `relatedpostid` BIGINT,
    `linktypeid` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_posts` (
    `id` BIGINT,
    `posttypeid` BIGINT,
    `acceptedanswerid` BIGINT,
    `creaiondate` DATETIME,
    `score` BIGINT,
    `viewcount` BIGINT,
    `body` STRING,
    `owneruserid` BIGINT,
    `lasactivitydate` DATETIME,
    `title` STRING,
    `tags` STRING,
    `answercount` BIGINT,
    `commentcount` BIGINT,
    `favoritecount` BIGINT,
    `lasteditoruserid` BIGINT,
    `lasteditdate` DATETIME,
    `communityowneddate` DATETIME,
    `parentid` BIGINT,
    `closeddate` DATETIME,
    `ownerdisplayname` STRING,
    `lasteditordisplayname` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_tags` (
    `id` BIGINT,
    `tagname` STRING,
    `count` BIGINT,
    `excerptpostid` BIGINT,
    `wikipostid` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_users` (
    `id` BIGINT,
    `reputation` BIGINT,
    `creationdate` DATETIME,
    `displayname` STRING,
    `lastaccessdate` DATETIME,
    `websiteurl` STRING,
    `location` STRING,
    `aboutme` STRING,
    `views` BIGINT,
    `upvotes` BIGINT,
    `downvotes` BIGINT,
    `accountid` BIGINT,
    `age` BIGINT,
    `profileimageurl` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_codebase_community_votes` (
    `id` BIGINT,
    `postid` BIGINT,
    `votetypeid` BIGINT,
    `creationdate` DATE,
    `userid` BIGINT,
    `bountyamount` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_debit_card_specializing_customers` (
    `customerid` BIGINT,
    `segment` STRING,
    `currency` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`customerid`) DISTRIBUTED BY HASH(`customerid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_debit_card_specializing_gasstations` (
    `gasstationid` BIGINT,
    `chainid` BIGINT,
    `country` STRING,
    `segment` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`gasstationid`) DISTRIBUTED BY HASH(`gasstationid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_debit_card_specializing_products` (
    `productid` BIGINT,
    `description` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`productid`) DISTRIBUTED BY HASH(`productid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_debit_card_specializing_transactions_1k` (
    `transactionid` BIGINT,
    `date` DATE,
    `time` STRING,
    `customerid` BIGINT,
    `cardid` BIGINT,
    `gasstationid` BIGINT,
    `productid` BIGINT,
    `amount` BIGINT,
    `price` FLOAT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`transactionid`) DISTRIBUTED BY HASH(`transactionid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_debit_card_specializing_yearmonth` (
    `customerid` BIGINT,
    `date` STRING,
    `consumption` FLOAT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`customerid`) DISTRIBUTED BY HASH(`customerid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_country` (
    `id` BIGINT,
    `name` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_league` (
    `id` BIGINT,
    `country_id` BIGINT,
    `name` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_match` (
    `id` BIGINT,
    `country_id` BIGINT,
    `league_id` BIGINT,
    `season` STRING,
    `stage` BIGINT,
    `date` STRING,
    `match_api_id` BIGINT,
    `home_team_api_id` BIGINT,
    `away_team_api_id` BIGINT,
    `home_team_goal` BIGINT,
    `away_team_goal` BIGINT,
    `home_player_x1` BIGINT,
    `home_player_x2` BIGINT,
    `home_player_x3` BIGINT,
    `home_player_x4` BIGINT,
    `home_player_x5` BIGINT,
    `home_player_x6` BIGINT,
    `home_player_x7` BIGINT,
    `home_player_x8` BIGINT,
    `home_player_x9` BIGINT,
    `home_player_x10` BIGINT,
    `home_player_x11` BIGINT,
    `away_player_x1` BIGINT,
    `away_player_x2` BIGINT,
    `away_player_x3` BIGINT,
    `away_player_x4` BIGINT,
    `away_player_x5` BIGINT,
    `away_player_x6` BIGINT,
    `away_player_x7` BIGINT,
    `away_player_x8` BIGINT,
    `away_player_x9` BIGINT,
    `away_player_x10` BIGINT,
    `away_player_x11` BIGINT,
    `home_player_y1` BIGINT,
    `home_player_y2` BIGINT,
    `home_player_y3` BIGINT,
    `home_player_y4` BIGINT,
    `home_player_y5` BIGINT,
    `home_player_y6` BIGINT,
    `home_player_y7` BIGINT,
    `home_player_y8` BIGINT,
    `home_player_y9` BIGINT,
    `home_player_y10` BIGINT,
    `home_player_y11` BIGINT,
    `away_player_y1` BIGINT,
    `away_player_y2` BIGINT,
    `away_player_y3` BIGINT,
    `away_player_y4` BIGINT,
    `away_player_y5` BIGINT,
    `away_player_y6` BIGINT,
    `away_player_y7` BIGINT,
    `away_player_y8` BIGINT,
    `away_player_y9` BIGINT,
    `away_player_y10` BIGINT,
    `away_player_y11` BIGINT,
    `home_player_1` BIGINT,
    `home_player_2` BIGINT,
    `home_player_3` BIGINT,
    `home_player_4` BIGINT,
    `home_player_5` BIGINT,
    `home_player_6` BIGINT,
    `home_player_7` BIGINT,
    `home_player_8` BIGINT,
    `home_player_9` BIGINT,
    `home_player_10` BIGINT,
    `home_player_11` BIGINT,
    `away_player_1` BIGINT,
    `away_player_2` BIGINT,
    `away_player_3` BIGINT,
    `away_player_4` BIGINT,
    `away_player_5` BIGINT,
    `away_player_6` BIGINT,
    `away_player_7` BIGINT,
    `away_player_8` BIGINT,
    `away_player_9` BIGINT,
    `away_player_10` BIGINT,
    `away_player_11` BIGINT,
    `goal` STRING,
    `shoton` STRING,
    `shotoff` STRING,
    `foulcommit` STRING,
    `card` STRING,
    `cross` STRING,
    `corner` STRING,
    `possession` STRING,
    `b365h` FLOAT,
    `b365d` FLOAT,
    `b365a` FLOAT,
    `bwh` FLOAT,
    `bwd` FLOAT,
    `bwa` FLOAT,
    `iwh` FLOAT,
    `iwd` FLOAT,
    `iwa` FLOAT,
    `lbh` FLOAT,
    `lbd` FLOAT,
    `lba` FLOAT,
    `psh` FLOAT,
    `psd` FLOAT,
    `psa` FLOAT,
    `whh` FLOAT,
    `whd` FLOAT,
    `wha` FLOAT,
    `sjh` FLOAT,
    `sjd` FLOAT,
    `sja` FLOAT,
    `vch` FLOAT,
    `vcd` FLOAT,
    `vca` FLOAT,
    `gbh` FLOAT,
    `gbd` FLOAT,
    `gba` FLOAT,
    `bsh` FLOAT,
    `bsd` FLOAT,
    `bsa` FLOAT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_player` (
    `id` BIGINT,
    `player_api_id` BIGINT,
    `player_name` STRING,
    `player_fifa_api_id` BIGINT,
    `birthday` STRING,
    `height` BIGINT,
    `weight` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_player_attributes` (
    `id` BIGINT,
    `player_fifa_api_id` BIGINT,
    `player_api_id` BIGINT,
    `date` STRING,
    `overall_rating` BIGINT,
    `potential` BIGINT,
    `preferred_foot` STRING,
    `attacking_work_rate` STRING,
    `defensive_work_rate` STRING,
    `crossing` BIGINT,
    `finishing` BIGINT,
    `heading_accuracy` BIGINT,
    `short_passing` BIGINT,
    `volleys` BIGINT,
    `dribbling` BIGINT,
    `curve` BIGINT,
    `free_kick_accuracy` BIGINT,
    `long_passing` BIGINT,
    `ball_control` BIGINT,
    `acceleration` BIGINT,
    `sprint_speed` BIGINT,
    `agility` BIGINT,
    `reactions` BIGINT,
    `balance` BIGINT,
    `shot_power` BIGINT,
    `jumping` BIGINT,
    `stamina` BIGINT,
    `strength` BIGINT,
    `long_shots` BIGINT,
    `aggression` BIGINT,
    `interceptions` BIGINT,
    `positioning` BIGINT,
    `vision` BIGINT,
    `penalties` BIGINT,
    `marking` BIGINT,
    `standing_tackle` BIGINT,
    `sliding_tackle` BIGINT,
    `gk_diving` BIGINT,
    `gk_handling` BIGINT,
    `gk_kicking` BIGINT,
    `gk_positioning` BIGINT,
    `gk_reflexes` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_team` (
    `id` BIGINT,
    `team_api_id` BIGINT,
    `team_fifa_api_id` BIGINT,
    `team_long_name` STRING,
    `team_short_name` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_european_football_2_team_attributes` (
    `id` BIGINT,
    `team_fifa_api_id` BIGINT,
    `team_api_id` BIGINT,
    `date` STRING,
    `buildupplayspeed` BIGINT,
    `buildupplayspeedclass` STRING,
    `buildupplaydribbling` BIGINT,
    `buildupplaydribblingclass` STRING,
    `buildupplaypassing` BIGINT,
    `buildupplaypassingclass` STRING,
    `buildupplaypositioningclass` STRING,
    `chancecreationpassing` BIGINT,
    `chancecreationpassingclass` STRING,
    `chancecreationcrossing` BIGINT,
    `chancecreationcrossingclass` STRING,
    `chancecreationshooting` BIGINT,
    `chancecreationshootingclass` STRING,
    `chancecreationpositioningclass` STRING,
    `defencepressure` BIGINT,
    `defencepressureclass` STRING,
    `defenceaggression` BIGINT,
    `defenceaggressionclass` STRING,
    `defenceteamwidth` BIGINT,
    `defenceteamwidthclass` STRING,
    `defencedefenderlineclass` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_account` (
    `account_id` BIGINT,
    `district_id` BIGINT,
    `frequency` STRING,
    `date` DATE,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`account_id`) DISTRIBUTED BY HASH(`account_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_card` (
    `card_id` BIGINT,
    `disp_id` BIGINT,
    `type` STRING,
    `issued` DATE,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`card_id`) DISTRIBUTED BY HASH(`card_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_client` (
    `client_id` BIGINT,
    `gender` STRING,
    `birth_date` DATE,
    `district_id` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`client_id`) DISTRIBUTED BY HASH(`client_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_disp` (
    `disp_id` BIGINT,
    `client_id` BIGINT,
    `account_id` BIGINT,
    `type` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`disp_id`) DISTRIBUTED BY HASH(`disp_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_district` (
    `district_id` BIGINT,
    `a2` STRING,
    `a3` STRING,
    `a4` STRING,
    `a5` STRING,
    `a6` STRING,
    `a7` STRING,
    `a8` BIGINT,
    `a9` BIGINT,
    `a10` FLOAT,
    `a11` BIGINT,
    `a12` FLOAT,
    `a13` FLOAT,
    `a14` BIGINT,
    `a15` BIGINT,
    `a16` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`district_id`) DISTRIBUTED BY HASH(`district_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_loan` (
    `loan_id` BIGINT,
    `account_id` BIGINT,
    `date` DATE,
    `amount` BIGINT,
    `duration` BIGINT,
    `payments` FLOAT,
    `status` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`loan_id`) DISTRIBUTED BY HASH(`loan_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_order` (
    `order_id` BIGINT,
    `account_id` BIGINT,
    `bank_to` STRING,
    `account_to` BIGINT,
    `amount` FLOAT,
    `k_symbol` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`order_id`) DISTRIBUTED BY HASH(`order_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_financial_trans` (
    `trans_id` BIGINT,
    `account_id` BIGINT,
    `date` DATE,
    `type` STRING,
    `operation` STRING,
    `amount` BIGINT,
    `balance` BIGINT,
    `k_symbol` STRING,
    `bank` STRING,
    `account` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`trans_id`) DISTRIBUTED BY HASH(`trans_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_circuits` (
    `circuitid` BIGINT,
    `circuitref` STRING,
    `name` STRING,
    `location` STRING,
    `country` STRING,
    `lat` FLOAT,
    `lng` FLOAT,
    `alt` BIGINT,
    `url` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`circuitid`) DISTRIBUTED BY HASH(`circuitid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_constructorresults` (
    `constructorresultsid` BIGINT,
    `raceid` BIGINT,
    `constructorid` BIGINT,
    `points` FLOAT,
    `status` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`constructorresultsid`) DISTRIBUTED BY HASH(`constructorresultsid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_constructors` (
    `constructorid` BIGINT,
    `constructorref` STRING,
    `name` STRING,
    `nationality` STRING,
    `url` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`constructorid`) DISTRIBUTED BY HASH(`constructorid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_constructorstandings` (
    `constructorstandingsid` BIGINT,
    `raceid` BIGINT,
    `constructorid` BIGINT,
    `points` FLOAT,
    `position` BIGINT,
    `positiontext` STRING,
    `wins` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`constructorstandingsid`) DISTRIBUTED BY HASH(`constructorstandingsid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_drivers` (
    `driverid` BIGINT,
    `driverref` STRING,
    `number` BIGINT,
    `code` STRING,
    `forename` STRING,
    `surname` STRING,
    `dob` DATE,
    `nationality` STRING,
    `url` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`driverid`) DISTRIBUTED BY HASH(`driverid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_driverstandings` (
    `driverstandingsid` BIGINT,
    `raceid` BIGINT,
    `driverid` BIGINT,
    `points` FLOAT,
    `position` BIGINT,
    `positiontext` STRING,
    `wins` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`driverstandingsid`) DISTRIBUTED BY HASH(`driverstandingsid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_laptimes` (
    `raceid` BIGINT,
    `driverid` BIGINT,
    `lap` BIGINT,
    `position` BIGINT,
    `time` STRING,
    `milliseconds` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`raceid`) DISTRIBUTED BY HASH(`raceid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_pitstops` (
    `raceid` BIGINT,
    `driverid` BIGINT,
    `stop` BIGINT,
    `lap` BIGINT,
    `time` STRING,
    `duration` STRING,
    `milliseconds` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`raceid`) DISTRIBUTED BY HASH(`raceid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_qualifying` (
    `qualifyid` BIGINT,
    `raceid` BIGINT,
    `driverid` BIGINT,
    `constructorid` BIGINT,
    `number` BIGINT,
    `position` BIGINT,
    `q1` STRING,
    `q2` STRING,
    `q3` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`qualifyid`) DISTRIBUTED BY HASH(`qualifyid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_races` (
    `raceid` BIGINT,
    `year` BIGINT,
    `round` BIGINT,
    `circuitid` BIGINT,
    `name` STRING,
    `date` DATE,
    `time` STRING,
    `url` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`raceid`) DISTRIBUTED BY HASH(`raceid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_results` (
    `resultid` BIGINT,
    `raceid` BIGINT,
    `driverid` BIGINT,
    `constructorid` BIGINT,
    `number` BIGINT,
    `grid` BIGINT,
    `position` BIGINT,
    `positiontext` STRING,
    `positionorder` BIGINT,
    `points` FLOAT,
    `laps` BIGINT,
    `time` STRING,
    `milliseconds` BIGINT,
    `fastestlap` BIGINT,
    `rank` BIGINT,
    `fastestlaptime` STRING,
    `fastestlapspeed` STRING,
    `statusid` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`resultid`) DISTRIBUTED BY HASH(`resultid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_seasons` (
    `year` BIGINT,
    `url` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`year`) DISTRIBUTED BY HASH(`year`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_formula_1_status` (
    `statusid` BIGINT,
    `status` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`statusid`) DISTRIBUTED BY HASH(`statusid`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_attendance` (
    `link_to_event` VARCHAR(65533),
    `link_to_member` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`link_to_event`) DISTRIBUTED BY HASH(`link_to_event`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_budget` (
    `budget_id` VARCHAR(65533),
    `category` STRING,
    `spent` FLOAT,
    `remaining` FLOAT,
    `amount` BIGINT,
    `event_status` STRING,
    `link_to_event` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`budget_id`) DISTRIBUTED BY HASH(`budget_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_event` (
    `event_id` VARCHAR(65533),
    `event_name` STRING,
    `event_date` STRING,
    `type` STRING,
    `notes` STRING,
    `location` STRING,
    `status` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`event_id`) DISTRIBUTED BY HASH(`event_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_expense` (
    `expense_id` VARCHAR(65533),
    `expense_description` STRING,
    `expense_date` STRING,
    `cost` FLOAT,
    `approved` STRING,
    `link_to_member` STRING,
    `link_to_budget` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`expense_id`) DISTRIBUTED BY HASH(`expense_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_income` (
    `income_id` VARCHAR(65533),
    `date_received` STRING,
    `amount` BIGINT,
    `source` STRING,
    `notes` STRING,
    `link_to_member` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`income_id`) DISTRIBUTED BY HASH(`income_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_major` (
    `major_id` VARCHAR(65533),
    `major_name` STRING,
    `department` STRING,
    `college` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`major_id`) DISTRIBUTED BY HASH(`major_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_member` (
    `member_id` VARCHAR(65533),
    `first_name` STRING,
    `last_name` STRING,
    `email` STRING,
    `position` STRING,
    `t_shirt_size` STRING,
    `phone` STRING,
    `zip` BIGINT,
    `link_to_major` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`member_id`) DISTRIBUTED BY HASH(`member_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_student_club_zip_code` (
    `zip_code` BIGINT,
    `type` STRING,
    `city` STRING,
    `county` STRING,
    `state` STRING,
    `short_state` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`zip_code`) DISTRIBUTED BY HASH(`zip_code`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_alignment` (
    `id` BIGINT,
    `alignment` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_attribute` (
    `id` BIGINT,
    `attribute_name` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_colour` (
    `id` BIGINT,
    `colour` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_gender` (
    `id` BIGINT,
    `gender` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_hero_attribute` (
    `hero_id` BIGINT,
    `attribute_id` BIGINT,
    `attribute_value` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`hero_id`) DISTRIBUTED BY HASH(`hero_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_hero_power` (
    `hero_id` BIGINT,
    `power_id` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`hero_id`) DISTRIBUTED BY HASH(`hero_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_publisher` (
    `id` BIGINT,
    `publisher_name` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_race` (
    `id` BIGINT,
    `race` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_superhero` (
    `id` BIGINT,
    `superhero_name` STRING,
    `full_name` STRING,
    `gender_id` BIGINT,
    `eye_colour_id` BIGINT,
    `hair_colour_id` BIGINT,
    `skin_colour_id` BIGINT,
    `race_id` BIGINT,
    `publisher_id` BIGINT,
    `alignment_id` BIGINT,
    `height_cm` BIGINT,
    `weight_kg` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_superhero_superpower` (
    `id` BIGINT,
    `power_name` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_thrombosis_prediction_examination` (
    `id` BIGINT,
    `Examination Date` DATE,
    `aCL IgG` FLOAT,
    `aCL IgM` FLOAT,
    `ana` BIGINT,
    `ANA Pattern` STRING,
    `aCL IgA` BIGINT,
    `diagnosis` STRING,
    `kct` STRING,
    `rvvt` STRING,
    `lac` STRING,
    `symptoms` STRING,
    `thrombosis` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_thrombosis_prediction_laboratory` (
    `id` BIGINT,
    `date` DATE,
    `got` BIGINT,
    `gpt` BIGINT,
    `ldh` BIGINT,
    `alp` BIGINT,
    `tp` FLOAT,
    `alb` FLOAT,
    `ua` FLOAT,
    `un` BIGINT,
    `cre` FLOAT,
    `T-BIL` FLOAT,
    `T-CHO` BIGINT,
    `tg` BIGINT,
    `cpk` BIGINT,
    `glu` BIGINT,
    `wbc` FLOAT,
    `rbc` FLOAT,
    `hgb` FLOAT,
    `hct` FLOAT,
    `plt` BIGINT,
    `pt` FLOAT,
    `aptt` BIGINT,
    `fg` FLOAT,
    `pic` BIGINT,
    `tat` BIGINT,
    `tat2` BIGINT,
    `U-PRO` STRING,
    `igg` BIGINT,
    `iga` BIGINT,
    `igm` BIGINT,
    `crp` STRING,
    `ra` STRING,
    `rf` STRING,
    `c3` BIGINT,
    `c4` BIGINT,
    `rnp` STRING,
    `sm` STRING,
    `sc170` STRING,
    `ssa` STRING,
    `ssb` STRING,
    `centromea` STRING,
    `dna` STRING,
    `DNA-II` BIGINT,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_thrombosis_prediction_patient` (
    `id` BIGINT,
    `sex` STRING,
    `birthday` DATE,
    `description` DATE,
    `First Date` DATE,
    `admission` STRING,
    `diagnosis` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`id`) DISTRIBUTED BY HASH(`id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_toxicology_atom` (
    `atom_id` VARCHAR(65533),
    `molecule_id` STRING,
    `element` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`atom_id`) DISTRIBUTED BY HASH(`atom_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_toxicology_bond` (
    `bond_id` VARCHAR(65533),
    `molecule_id` STRING,
    `bond_type` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`bond_id`) DISTRIBUTED BY HASH(`bond_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_toxicology_connected` (
    `atom_id` VARCHAR(65533),
    `atom_id2` STRING,
    `bond_id` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`atom_id`) DISTRIBUTED BY HASH(`atom_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS `ods_toxicology_molecule` (
    `molecule_id` VARCHAR(65533),
    `label` STRING,
    `__deleted` BOOLEAN,
    `__source_ts_ms` BIGINT
) DUPLICATE KEY(`molecule_id`) DISTRIBUTED BY HASH(`molecule_id`) BUCKETS 4
PROPERTIES ("replication_num" = "1");
