"""BIRD mini_dev table names per logical db_id (for single-schema / public loads on AWS)."""

from __future__ import annotations

# Source: BIRD mini_dev PostgreSQL schemas (11 databases, 75 tables total in public).
MINIDEV_DB_TABLES: dict[str, tuple[str, ...]] = {
    "california_schools": ("frpm", "satscores", "schools"),
    "card_games": ("cards", "foreign_data", "legalities", "rulings", "set_translations", "sets"),
    "codebase_community": (
        "badges",
        "comments",
        "posthistory",
        "postlinks",
        "posts",
        "tags",
        "users",
        "votes",
    ),
    "debit_card_specializing": (
        "customers",
        "gasstations",
        "products",
        "transactions_1k",
        "yearmonth",
    ),
    "european_football_2": (
        "country",
        "league",
        "match",
        "player",
        "player_attributes",
        "team",
        "team_attributes",
    ),
    "financial": ("account", "card", "client", "disp", "district", "loan", "order", "trans"),
    "formula_1": (
        "circuits",
        "constructorresults",
        "constructorstandings",
        "constructors",
        "driverstandings",
        "drivers",
        "laptimes",
        "pitstops",
        "qualifying",
        "races",
        "results",
        "seasons",
        "status",
    ),
    "student_club": (
        "attendance",
        "budget",
        "event",
        "expense",
        "income",
        "major",
        "member",
        "zip_code",
    ),
    "superhero": (
        "alignment",
        "attribute",
        "colour",
        "gender",
        "hero_attribute",
        "hero_power",
        "publisher",
        "race",
        "superhero",
        "superpower",
    ),
    "thrombosis_prediction": (
        "examination",
        "laboratory",
        "patient",
    ),
    "toxicology": ("atom", "bond", "connected", "molecule"),
}
